# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  servers = {
    'haproxy' => '192.168.33.10',
        'vm1' => '192.168.33.20',
        'vm2' => '192.168.33.30'
  }

  http_port = {
    'haproxy' => 8080,
        'vm1' => 8081,
        'vm2' => 8082
  }

  ssh_port = {
    'haproxy' => 3022,
        'vm1' => 3023,
        'vm2' => 3024
  }

  servers.each do |server_name, server_ip|
    config.vm.define server_name do |app_config|
      app_config.vm.hostname = "#{server_name.to_s}"
      app_config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
      app_config.vm.network :forwarded_port, guest: 22, host: ssh_port[server_name], auto_correct: true
      app_config.vm.network :forwarded_port, guest: 80, host: http_port[server_name], auto_correct: true
      app_config.vm.network :private_network, ip: "#{server_ip}"

      # virtualbox
      app_config.vm.provider :virtualbox do |v, override|
        override.vm.box = "ubuntu/trusty64"
        override.vm.box_check_update = false

        v.memory = 1024
        v.cpus = 2
      end
    end
  end
end
